wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702376618.25509
    t:
      1:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 6
      - 7
      - 8
      - 15
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
    visualize:
      conf_mat:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/confusion_matrix/v1
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
